#!/usr/bin/env python

import os, json

m = {'adoc': 'stylesheets', 'code': 'highlightjs'}


def main():
    r = {}
    for k, v in m.items():
        r[k] = sorted(
            [i.rsplit('.', 1)[0] for i in os.listdir(v) if i.endswith('.css')]
        )
    with open('index.txt', 'w') as f:
        f.write(json.dumps(r, indent=4, sort_keys=True))


if __name__ == '__main__':
    main()
